### ISSUE TITLE
Move endpoints in README to separate page

### ISSUE THREAD

**Issue by braddf** [openclimatefix/Elexonpy#44]
## Detailed Description / Context
At the moment, the README is cluttered with the exhaustive list of endpoints

## Possible Implementation
 If a user/contributor wants to check these, they can click through a clear link to see them, otherwise the rest of the README sections can remain un-dwarfed and easy to navigate!

**Comment by yousefsawy** [comment]
Hello, I have fixed this issue and created a pull request.

**Comment by peterdudfield** [comment]
Thanks @yousefsawy
