### ISSUE TITLE
What name to use

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/Elexonpy#9]
## Detailed Description
We should name this so its useful to the readers

## Context
- pyElexon is already taken on pypi

## Possible Implementation
- Perhaps we could rename this Elexonpy 
- other name suggestions are welcome

**Comment by 14Richa** [comment]
Hey @peterdudfield, Since pyElexon has already taken on PyPI, I've come up with some alternative names:

1. ElexonKit
2. ElexonHub
3. pyelexonapi
4. ElexonAPIWrapper
5. ElexonPyConnector

I also like Elexonpy, so that's another option we can consider. Let me know your thoughts.

**Comment by peterdudfield** [comment]
we went with `elexonpy`
